[tool.poetry]
name = "rxio"
version = "0.1.1"
description = "Flexible, predictable, async reactive programming in modern Python"
authors = ["Joren Hammudoglu <jhammudoglu@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jorenham/rxio"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-asyncio = "^0.19.0"
pyright = "^1.1.268"

[tool.poetry.dependencies.uvloop]
version = "^0.16"
markers = "sys_platform != 'win32' and implementation_name == 'cpython'"

[tool.pytest.ini_options]
addopts = "--maxfail=1"
asyncio_mode = "auto"

[tool.pyright]
pythonVersion = "3.9"
strictParameterNoneValue = false
include = ["rxio"]
exclude = [
    "**/__pycache__",
    ".pytest_cache",
    ".hypothesis",
    "tests",
    "dist",
]
venvPath = ".venv"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
